// frontend-react/src/PrintMap.tsx
import React, { useState } from 'react';

const PrintMap: React.FC = () => {
  const [cityName, setCityName] = useState('');

  const onPrint = async () => {
    try {
      const response = await fetch(`http://localhost:5295/api/render/city?name=${cityName}`, {
        method: 'GET',
      });
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${cityName}.pdf`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading PDF:', error);
    }
  };

  return (
    <div>
      <p>Print maps service: </p>
      <input
        type="text"
        value={cityName}
        onChange={(e) => setCityName(e.target.value)}
        placeholder="Enter city name"
      />
      <button onClick={onPrint}>Print</button>
    </div>
  );
};

export default PrintMap;

// frontend/src/app/print-map/print-map.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-print-map',
  imports: [FormsModule],
  templateUrl: './print-map.component.html',
  styleUrl: './print-map.component.css'
})
export class PrintMapComponent {
  cityName: string = '';
  constructor(private http: HttpClient) {}

  onprint() {
    this.http.get("http://localhost:5295/api/render/city?name=" + this.cityName, { responseType: "blob"}).subscribe((response: any) => {
      console.log(response);
      const blob = new Blob([response], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = this.cityName + '.pdf';
      a.click();
      window.URL.revokeObjectURL(url);
    });
  }
}

<p>Print maps service: </p>
<input type="text" [(ngModel)]="cityName" placeholder="Enter city name">
<button (click)="onprint()">Print</button>
